name: CD

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v2.0.0
      with:
        # pulls all commits (needed for lerna / semantic release to correctly version)
        fetch-depth: "0"
    # pulls all tags (needed for lerna / semantic release to correctly version)
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - run: git config --global user.email "@matt.j.dunn"
    - run: git config --global user.name "matt.j.dunn"
    - name: Install
      run: yarn install
    - name: Build & Release
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn cd
    env:
      CI: true


